site_name: HODL Project 
site_description: documentation for the HODL project
site_author: HODL Team

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Project Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Backend:
    - Overview: backend/overview.md
    - Project Structure: backend/project-structure.md
    - Models:
      - User: backend/models/user.md
      - Akita: backend/models/akita.md
      - Incufi: backend/models/incufi.md
      - Liquidity: backend/models/liquidity.md
      - Price: backend/models/price.md
      - NFT: backend/models/nft.md
    - APIs:
      - User: backend/apis/user.md
      - Akita: backend/apis/akita.md
      - Incufi: backend/apis/incufi.md
      - Liquidity: backend/apis/liquidity.md
    - Management Commands:
      - Overview: backend/management-commands/overview.md
      - Distribute Commission: backend/management-commands/distribute-commission.md
      - Distribute Gift: backend/management-commands/distribute-gift.md
      - Import NFTs: backend/management-commands/import-nfts.md
    - Migrations: backend/migrations.md
    - Signals: backend/signals.md
    - Admin Interface: backend/admin-interface.md
  - Frontend:
    - Overview: frontend/overview.md
    - Project Structure: frontend/project-structure.md
    - Pages:
      - Dashboard: frontend/pages/dashboard.md
      - My NFTs: frontend/pages/my-nfts.md
      - Stake: frontend/pages/stake.md
      - Swap: frontend/pages/swap.md
      - Team: frontend/pages/team.md
      - Bonus: frontend/pages/bonus.md
      - Complete Profile: frontend/pages/complete-profile.md
      - Register: frontend/pages/register.md
      - Projects: frontend/pages/projects.md
      - Withdraw History: frontend/pages/withdraw-history.md
    - Components:
      - Header: frontend/components/header.md
      - Sidebar: frontend/components/sidebar.md
      - Language Picker: frontend/components/language-picker.md
      - Navigation: frontend/components/navigation.md
      - User Profile: frontend/components/user-profile.md
    - Core:
      - Context: frontend/core/context.md
      - Localization: frontend/core/localization.md
      - Utils: frontend/core/utils.md
    - Styling:
      - CSS Modules: frontend/styling/css-modules.md
      - Global Styles: frontend/styling/global-styles.md
  - Blockchain:
    - Overview: blockchain/overview.md
    - Smart Contracts:
      - ERC20 Token: blockchain/contracts/erc20-token.md
      - NFT: blockchain/contracts/nft.md
      - Liquidity: blockchain/contracts/liquidity.md
      - Purchase: blockchain/contracts/purchase.md
      - Swap: blockchain/contracts/swap.md
    - ABIs:
      - Overview: blockchain/abis/overview.md
      - ERC20 Token: blockchain/abis/erc20-token.md
      - NFT: blockchain/abis/nft.md
      - Liquidity: blockchain/abis/liquidity.md
      - Purchase: blockchain/abis/purchase.md
      - Swap: blockchain/abis/swap.md
    - Transactions: blockchain/transactions.md
    - Integration with Backend: blockchain/backend-integration.md
    - Integration with Frontend: blockchain/frontend-integration.md
  - Development:
    - Setup: development/setup.md
    - Backend Development:
      - Environment Setup: development/backend/environment-setup.md
      - Adding New Models: development/backend/adding-models.md
      - Creating APIs: development/backend/creating-apis.md
      - Writing Management Commands: development/backend/management-commands.md
      - Testing: development/backend/testing.md
    - Frontend Development:
      - Environment Setup: development/frontend/environment-setup.md
      - Creating New Pages: development/frontend/creating-pages.md
      - State Management: development/frontend/state-management.md
      - Styling Components: development/frontend/styling-components.md
      - Testing: development/frontend/testing.md
    - Blockchain Development:
      - Local Blockchain Setup: development/blockchain/local-setup.md
      - Writing Smart Contracts: development/blockchain/writing-contracts.md
      - Testing Smart Contracts: development/blockchain/testing-contracts.md
      - Integrating with Web3: development/blockchain/web3-integration.md
  - Deployment:
    - Overview: deployment/overview.md
    - Backend Deployment:
      - Server Setup: deployment/backend/server-setup.md
      - Database Configuration: deployment/backend/database-config.md
      - WSGI Configuration: deployment/backend/wsgi-config.md
      - Nginx Configuration: deployment/backend/nginx-config.md
    - Frontend Deployment:
      - Build Process: deployment/frontend/build-process.md
      - Hosting Options: deployment/frontend/hosting-options.md
      - CI/CD Setup: deployment/frontend/ci-cd-setup.md
    - Smart Contract Deployment:
      - Testnet Deployment: deployment/blockchain/testnet-deployment.md
      - Mainnet Deployment: deployment/blockchain/mainnet-deployment.md
      - Verifying Contracts: deployment/blockchain/contract-verification.md
  - API Reference:
    - Backend APIs: api-reference/backend-apis.md
    - Frontend Components: api-reference/frontend-components.md
    - Smart Contract Functions: api-reference/smart-contract-functions.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md
  - Contributing:
    - Guidelines: contributing/guidelines.md
    - Code of Conduct: contributing/code-of-conduct.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - redirects:
      redirect_maps:
        'old_page.md': 'new_page.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/hodl-project
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hodlproject
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: Copyright &copy; 2024 HODL Project Team